### ISSUE TITLE
Service Mesh

### ISSUE THREAD

**Issue by syslot** [iflytek/aiges#12]
Hi, wei.
This is an amazing and useful tool and I want to know can I use service mesh framework in this project? 

Thx.

**Comment by scw00** [comment]
Of course you can. The sidercar of Service Mesh can be transparent proxy which manage your traffic to different AtheGate, AthProxy, and AtheLoader etc. 

Actually Service Mesh  doesn't care which project you use. It only care which protocol you use (TCP, HTTP, GRP and H2 etc). And it use iptable to forward your ingress traffic and egress traffic to sidercar.  Sidercar decide which service to transfer via dns .
