### ISSUE TITLE
[bug] Crash when no parameters passed

### ISSUE THREAD

**Issue by whybeyoung** [iflytek/aiges#26]
when user doesn't supply the function parameters, https://github.com/xfyun/aiges/blob/5364e44aaea2771c34991a2c97e4f5834f93fa90/ai_cpython_wrapper/wrapper.cpp#L151 will crashed

**Comment by happened** [comment]
because  widget/adapter_c.go/paramListCreate () . this init func   set param's key and param's value be NULL .
this crash only occur when param or data is empty
