### ISSUE TITLE
功能需求讨论

### ISSUE THREAD

**Issue by happened** [iflytek/aiges#31]
1. 升级至模型即服务是否考虑支持多模型编排
2. 支持python,cpp预后处理脚本仓库建设，支持onnx runtime推理框架 或自定义推理backend
3. python推理多进程支持 multiprocessing 执行exec

**Comment by whybeyoung** [comment]
> 1. 升级至模型即服务是否考虑支持多模型编排
> 2. 支持python,cpp预后处理脚本仓库建设，支持onnx runtime推理框架 或自定义推理backend
> 3. python推理多进程支持 multiprocessing 执行exec

We will  discuss this feature these days .  @acpan
