### ISSUE TITLE
 problems when using CTRL+C to stop the program

### ISSUE THREAD

**Issue by sea-wyq** [iflytek/aiges#41]
The aiges loader process cannot be closed with ctrl + c, and the kill command is also required. We have this problem inside the docker container.

**Comment by sea-wyq** [comment]
fixed

**Comment by whybeyoung** [comment]
@sea-wyq  please make the title more readable.

**Comment by sea-wyq** [comment]
fixed:issue https://github.com/xfyun/aiges/issues/41

**Comment by whybeyoung** [comment]
@sqjian 
I just learned that signal.INT is captured in xsf. Do you have any suggestions for this?

**Comment by whybeyoung** [comment]
close this beacuse of handled in the xsf framework
