### ISSUE TITLE
[Bug]: init wrapper error

### ISSUE THREAD

**Issue by hjnlxuexi** [iflytek/aiges#76]
### What happened?

use command to init wrapper:
python3 -m aiges create -n mnist

wrapper.py 
-->class UserRequest
---->input2 = StringBodyField(key="switch", value="ctrl")

ERROR:  StringBodyField value must be bytes String...
input2 = StringBodyField(key="switch", value="ctrl")

**Comment by whybeyoung** [comment]
fix in the latest aiges package
